[workspace]
members = [
    "hive-commons",
    "hive-webapp",
    "hive-accounts-svc",
    "hive-messages-svc",
]

exclude = [
# exclude client for now
    "hive-webclient",
]

#TODO actual opt-level should be 3 -> optimised for wasm
[profile.release]
lto = true
opt-level = "s"
