[workspace]
members = [
    "hive-crypto",
    "hive-grpc",
    "hive-postgres-wrapper",
    "hive-server-embedded",
    "hive-svc-accounts",
]

exclude = [
    "hive-webapp",
# exclude client for now
    "hive-webclient"
]