
version: "3.8"
services:
    accounts_db:
        image: postgres:latest
        restart: always
        environment:
            POSTGRES_PASSWORD: accounts_db
            POSTGRES_DB: common
        healthcheck:
            test: [ "CMD", "pg_isready", "-q", "-d", "common", "-U", "postgres" ]

    messages_db:
        image: postgres:latest
        restart: always
        environment:
            POSTGRES_PASSWORD: messages_db
            POSTGRES_DB: common
        healthcheck:
            test: [ "CMD", "pg_isready", "-q", "-d", "common", "-U", "postgres" ]

    envoy_client_gateway:
        build:
            context: ./
            dockerfile: docker/Dockerfile.envoy
        restart: always
        ports:
            - "8080:10000"
            - "9901:9901"

    app_server:
        build:
            context: ./
            dockerfile: docker/Dockerfile.webapp
        volumes:
            - type: bind
              source: ./hive-commons
              target: /app/hive-commons
            - type: bind
              source: ./hive-webapp
              target: /app/hive-webapp
        restart: always
        command: npm run serve --prefix /app/hive-webapp

    accounts_svc:
        depends_on:
            accounts_db:
                condition: service_healthy
        restart: always
        build:
            context: ./
            args:
                PROJECT_NAME: hive-accounts-svc
            dockerfile: docker/debug/Dockerfile.services
        volumes:
            - type: bind
              source: ./hive-commons/certificate.json
              target: /certificate.json
            - type: bind
              source: ./hive-commons/privates.json
              target: /privates.json
        environment:
            - 'CONFIG={
            "port":8080,
            "loglevel":"debug",
            "db_config":{
                "host":"accounts_db",
                "port":5432,
                "user":"postgres",
                "password":"accounts_db",
                "dbname":"common",
                "ssl_mode":true},
            "certificate":"/certificate.json",
            "key":"/privates.json"
            }'

    messages_svc:
        depends_on:
            messages_db:
                condition: service_healthy
        restart: always
        build:
            context: ./
            args:
                PROJECT_NAME: hive-messages-svc
            dockerfile: docker/debug/Dockerfile.services
        environment:
            - 'CONFIG={
            "port":8080,
            "loglevel":"debug",
            "db_config":{
                "host":"messages_db",
                "port":5432,
                "user":"postgres",
                "password":"messages_db",
                "dbname":"common",
                "ssl_mode":true},
            "certificate":"ignore",
            "key":"ignore"
            }'
